
BRANCH_DOOM = 1
BRANCH_MINES = 2
BRANCH_SOKOBAN = 3

SPECIAL_TOP = 1
SPECIAL_DOOM_FORK = 2
SPECIAL_ORACLE = 3
SPECIAL_SOKOBAN_FORK = 4
SPECIAL_ROGUE = 5
SPECIAL_MINETOWN = 10
SPECIAL_MINES_END = 11

